### PR TITLE
passing

### PR DESCRIPTION
**Pull request by RnbWd**
I was able to get this pass test using `decomment` v4. I couldn't get v5 or the `trim` option to work, but `safety` works and I think this can be used as a plugin? I assume the current isn't working based on the `package.json`

### CODE REVIEW

**Comment by vitaly-t** [comment]
You know, you could just create your own `gulp-decomment`, and I would transfer its NPM ownership to you ;)

P.S. I'm off for the day, Happy New Year! :)

**Comment by RnbWd** [comment]
meh maybe

**Comment by vitaly-t** [comment]
Ok, just before I'm gone for the day, I've just added you as collaborator for this project, so you won't need my approval for changes ;)

**Comment by RnbWd** [comment]
thx, I want this working w/ v5 I'm modifying `strip-comments` to use v4

**Comment by vitaly-t** [comment]
Was there a problem switching to version 0.5 instead?

**Comment by vitaly-t** [comment]
@RnbWd See the protocol changes I made with [version 0.6.0 release](https://github.com/vitaly-t/decomment/releases/tag/v.0.6.0).

**Comment by vitaly-t** [comment]
@RnbWd Version 6.2 is just about perfect. I'm quite happy with the final result, to me it looks logically finished. Have a look ;) I think it is ready for prime time :)

**Comment by RnbWd** [comment]
It just wasn't working on my local env for some reason. Setting up the structure was most important, it shouldn't need any modification other than changing the `package.json` dependency, I'll test it now.

**Comment by RnbWd** [comment]
seems to work - i just pushed it

**Comment by RnbWd** [comment]
woops wrong repo

**Comment by vitaly-t** [comment]
:)

**Comment by RnbWd** [comment]
hmmmm i wonder if we can detect files in the gulp stream as input and try to use smart defaults based on the file extension... i just updated the readme but haven't implemented the html/text methods yet

**Comment by vitaly-t** [comment]
probably not, since it is expecting any text file, there is no way to tell a CSS from a regular Text file.

can we not pass parameters for gulp somehow?

**Comment by vitaly-t** [comment]
I still don't know enough about gulp to make any suggestion :( so I trust you can figure it out :)

**Comment by RnbWd** [comment]
yeah we can, the options object is passed in automatically, but the text/html methods could be implemented like the library normally `decomment.text` - or passed in as an option {`text: true}` - but as the file is parsed by gulp I have access to the file extension and metadata, so we could have like 'smart' defaults that are easily overridden, at least for html

**Comment by RnbWd** [comment]
technically everything but I don't want to make too many assumptions about the file based on it's extension - this could be default behavior or explicitly turned on via an option

**Comment by vitaly-t** [comment]
Can it not be something like this? - 

``` js
var gulp = require('gulp');
var decomment = require('gulp-decomment');

gulp.task('default', function () {
  return gulp.src('template.js')
    .pipe(decomment.text())
    .pipe(gulp.dest('dist'));
});
```

and

``` js
var gulp = require('gulp');
var decomment = require('gulp-decomment');

gulp.task('default', function () {
  return gulp.src('template.js')
    .pipe(decomment.html())
    .pipe(gulp.dest('dist'));
});
```

?

**Comment by RnbWd** [comment]
yeah i've used gulp plugins that work like that, so I know it's possible just need to change how the module's exported

**Comment by vitaly-t** [comment]
I would guess it is similar to how decomment is exporting itself: [index.js](https://github.com/vitaly-t/decomment/blob/master/lib/index.js).

**Comment by RnbWd** [comment]
yeah I just copied that syntax

**Comment by vitaly-t** [comment]
I've just checked in a little refactoring on that code ;)

**Comment by RnbWd** [comment]
yeah i was lazy and thinking about that - probably shouldn't be coding right now (different time zones) - but it's NEW YEARS haha

**Comment by vitaly-t** [comment]
Take you time, and Happy New Year. We can get back to it later :)

**Comment by vitaly-t** [comment]
@RnbWd I took my time today testing the shit out of `decomment`, and I found whole 2 bugs, did 2 releases since, now everything is fixed within 0.6.4. Can't find any issue no more.

Just keep in mind there were at least 3 important bug fixes since version 0.4.2, in case you reconsider it for `gulp-strip-comments` and move it to the latest `decomment` instead. It would be a good idea.

**Comment by RnbWd** [comment]
yeah I agree that seems like a good idea

**Comment by RnbWd** [comment]
thanks for all your hard work!

**Comment by vitaly-t** [comment]
I'm now kind of divided what to do with gulp-decomment, with the latest gulp-strip-comment it makes sense only to support one of them. :)

Perhaps it is worth finishing after all, because I also wanted to do `grunt-decomment` later.

**Comment by vitaly-t** [comment]
@RnbWd I saw a special test case in my dream, not sure which one was more weird - the case or the dream. Had to do another fix for that in [0.6.5](https://github.com/vitaly-t/decomment/releases/tag/v.0.6.5).

**Comment by RnbWd** [comment]
All of the 0.6.x patches will be downloaded automatically b/c of the ^ tag in the package.json - that's a weird dream haba

**Comment by vitaly-t** [comment]
Yeah, but the final version was 0.7.0. Ops! Sorry! :)

Anyway, I checked in that change into your project this morning ;)

**Comment by vitaly-t** [comment]
@RnbWd [grunt-decomment](https://github.com/vitaly-t/grunt-decomment) has been released for completeness ;)

**Pull request merged**
